CREATE DATABASE Lab10
DROP DATABASE Lab10
ALTER DATABASE Lab10 MODIFY Name= LAB10

CREATE TABLE CLASS1(
col1 int unique, 
col2 varchar(50) not null
);
INSERT INTO CLASS1 VALUES(3,'ABC')
SELECT * FROM CLASS1

TRUNCATE TABLE CLASS1

BACKUP DATABASE LAB10 TO DISK = 'D:\file_name.bak';

BACKUP DATABASE LAB10 TO DISK = 'D:\file_name1.bak' WITH DIFFERENTIAL;